In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.style as style
import matplotlib.ticker as mtick

In [2]:
df = pd.read_excel('dataset_combine_notna.xlsx')

In [3]:
df.head()

,Unnamed: 0,country,year,iso_code,population,SI.POV.GAPS,SI.POV.GINI,SI.POV.LMIC.GP,SI.POV.MDIM,SI.POV.MDIM.17.XQ,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,0,Afghanistan,1900,AFG,4832414,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,Afghanistan,1901,AFG,4879685,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Afghanistan,1902,AFG,4935122,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,Afghanistan,1903,AFG,4998861,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,Afghanistan,1904,AFG,5063419,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22343 entries, 0 to 22342
Columns: 144 entries, Unnamed: 0 to wind_share_energy
dtypes: float64(138), int64(4), object(2)
memory usage: 24.5+ MB

In [20]:
df2 = df[['year','iso_code','population','SI.POV.GAPS','SI.POV.GINI','SI.POV.LMIC.GP','SI.POV.MDIM','SI.POV.MDIM.17.XQ','SI.POV.MDIM.FE','SI.POV.MDIM.HH','SI.POV.MDIM.IT','SI.POV.MDIM.MA']]

In [21]:
df2

,year,iso_code,population,SI.POV.GAPS,SI.POV.GINI,SI.POV.LMIC.GP,SI.POV.MDIM,SI.POV.MDIM.17.XQ,SI.POV.MDIM.FE,SI.POV.MDIM.HH,SI.POV.MDIM.IT,SI.POV.MDIM.MA
0,1900,AFG,4832414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1901,AFG,4879685,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1902,AFG,4935122,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1903,AFG,4998861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1904,AFG,5063419,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
22338,2017,ZWE,14236599,9.4,44.3,25.9,0.0,0.0,0.0,0.0,0.0,0.0
22339,2018,ZWE,14438812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22340,2019,ZWE,14645473,13.5,50.3,29.9,0.0,0.0,0.0,0.0,0.0,0.0
22341,2020,ZWE,14862927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22342,2021,ZWE,15092171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df.iloc[:, 9:22]

,SI.POV.MDIM.17.XQ,SI.POV.MDIM.FE,SI.POV.MDIM.HH,SI.POV.MDIM.IT,SI.POV.MDIM.MA,SI.POV.MDIM.XQ,SI.POV.NAHC,SI.POV.UMIC,SN.ITK.DEFC.ZS,SN.ITK.MSFI.ZS,SN.ITK.SVFI.ZS,gdp,biofuel_cons_change_pct
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22338,0.0,0.0,0.0,0.0,0.0,0.0,30.4,84.1,0.0,67.0,35.9,21947836416,0.0
22339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.7,34.2,22715353088,0.0
22340,0.0,0.0,0.0,0.0,0.0,0.0,38.3,85.0,0.0,69.8,32.1,0,0.0
22341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73.0,31.3,0,0.0
22342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0